/* Mansions of Madness Casebook — the built-in list of official scenarios (Mansions of Madness Second Edition app),
   grouped by the product that unlocks them, plus the official investigators.
   Valkyrie scenarios are built in from js/valkyrie.js; others can be added on the admin page (shared) or by each player (just theirs).
   Investigators are a fixed official list: plays can only name these. */
(function(root){
'use strict';
var PRODUCTS=[
  {id:'core',name:'Core game',scenarios:['Escape from Innsmouth','Shattered Bonds','Cycle of Eternity','Rising Tide']},
  {id:'dlc',name:'Digital (app purchase)',scenarios:['What Lies Within','Dark Reflections','Altered Fates','Turn of a Page']},
  {id:'rn',name:'Recurring Nightmares',scenarios:['Dearly Departed']},
  {id:'sm',name:'Suppressed Memories',scenarios:['Cult of Sentinel Hill']},
  {id:'btt',name:'Beyond the Threshold',scenarios:['Gates of Silverwood Manor','Vengeful Impulses']},
  {id:'soa',name:'Streets of Arkham',scenarios:['Astral Alchemy','Gangs of Arkham','Ill-Fated Exhibit']},
  {id:'sot',name:'Sanctum of Twilight',scenarios:['The Twilight Diadem','Behind Closed Doors']},
  {id:'hj',name:'Horrific Journeys',scenarios:['Murder on the Stargazer Majestic','10:50 to Arkham','Hidden Depths']},
  {id:'pots',name:'Path of the Serpent',scenarios:['The Jungle Awakens','Into the Dark','Lost Temple of Yig']}
];
// The official Second Edition investigators, by the product that includes them. Only these can be saved on a play
// (firestore.rules holds the same list; test/house-rules.test.js checks they match). Sources: Valkyrie's content data
// (github.com/NPBruce/valkyrie, content/MoM/*/investigators.ini) for the core game and expansions; the publisher's
// product lists for the two figure collections.
var INVESTIGATOR_GROUPS=[
  {product:'core',name:'Core game',list:['Agatha Crane','Carson Sinclair','Father Mateo','Minh Thi Phan','Preston Fairmont','Rita Young','Wendy Adams','William Yorick']},
  {product:'rn',name:'Recurring Nightmares',list:['"Ashcan" Pete','Gloria Goldberg','Harvey Walters','Jenny Barnes','Joe Diamond','Kate Winthrop','Michael McGlen','Sister Mary']},
  {product:'sm',name:'Suppressed Memories',list:['Amanda Sharpe','Bob Jenkins','Carolyn Fern','Darrell Simmons','Dexter Drake','Mandy Thompson','Monterey Jack','Vincent Lee']},
  {product:'btt',name:'Beyond the Threshold',list:['Akachi Onyele','Wilson Richards']},
  {product:'soa',name:'Streets of Arkham',list:['Diana Stanley','Finn Edwards','Marie Lambeau','Tommy Muldoon']},
  {product:'sot',name:'Sanctum of Twilight',list:['Charlie Kane','Lily Chen']},
  {product:'hj',name:'Horrific Journeys',list:['Agnes Baker','Jim Culver','Silas Marsh','Trish Scarborough']},
  {product:'pots',name:'Path of the Serpent',list:['Daniela Reyes','Leo Anderson','Norman Withers','Ursula Downs']}
];
var INVESTIGATORS=[];INVESTIGATOR_GROUPS.forEach(function(g){INVESTIGATORS=INVESTIGATORS.concat(g.list);});

// Stable id from a scenario name: lowercase letters and digits joined by dashes ("10:50 to Arkham" -> "10-50-to-arkham").
function slug(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g,'').replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'scenario';}
// Loose key for matching names typed in different ways ("The Ill Fated Exhibit" = "Ill-Fated Exhibit").
function key(s){return slug(s).replace(/^the-/,'').replace(/-/g,'');}

var OFFICIAL=[];
PRODUCTS.forEach(function(p){p.scenarios.forEach(function(n){OFFICIAL.push({id:'o-'+slug(n),name:n,type:'official',product:p.id});});});

// Compare names ignoring case, quotes and punctuation ("Ashcan Pete" = '"Ashcan" Pete').
function invKey(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]+/g,' ').replace(/\s+/g,' ').trim();}
function isInvestigator(s){return INVESTIGATORS.indexOf(s)>=0;}
// The official investigator a typed name means, or '' if it isn't one (or is ambiguous).
// "Tommy" -> Tommy Muldoon, "Pete"/"Ashcan Pete" -> "Ashcan" Pete, "Mateo" -> Father Mateo, "?" -> ''.
function matchInvestigator(s){
  var k=invKey(s);if(!k)return '';
  var exact=INVESTIGATORS.filter(function(n){return invKey(n)===k;});if(exact.length)return exact[0];
  var word=INVESTIGATORS.filter(function(n){return invKey(n).split(' ').indexOf(k)>=0;});if(word.length===1)return word[0];
  var pre=INVESTIGATORS.filter(function(n){return invKey(n).indexOf(k)===0;});if(pre.length===1)return pre[0];
  var all=INVESTIGATORS.filter(function(n){var w=invKey(n).split(' ');return k.split(' ').every(function(t){return w.indexOf(t)>=0;});});
  return all.length===1?all[0]:'';
}

// Valkyrie scenarios come from js/valkyrie.js (generated by scripts/fetch-valkyrie.py), loaded before this file.
var VALKYRIE=(root.MOM_VALKYRIE||[]).map(function(s){var o={};for(var k in s)if(k!=='key')o[k]=s[k];o.builtin=true;return o;});

// Find which real scenario a typed name means. Returns candidates best first: [{s, score}] with score 0..1.
// Exact (ignoring case, punctuation and a leading "The") scores 1; then shared words and spelling closeness,
// so "Altered Fate" finds Altered Fates and "Murder on the Stargazer" finds Murder on the Stargazer Majestic.
var STOP={the:1,of:1,a:1,an:1,to:1,at:1,in:1,on:1,and:1,de:1,la:1,el:1,do:1,da:1};
function words(s){return slug(s).split('-').filter(function(w){return w&&!STOP[w];});}
function lev(a,b){var m=a.length,n=b.length,d=[],i,j;if(!m)return n;if(!n)return m;for(j=0;j<=n;j++)d[j]=j;
  for(i=1;i<=m;i++){var prev=d[0];d[0]=i;for(j=1;j<=n;j++){var t=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=t;}}return d[n];}
function matchScenarios(name,list){
  var k=key(name),w=words(name);if(!k)return [];
  return list.map(function(s){
    var sk=key(s.name);if(sk===k)return {s:s,score:1};
    var sw=words(s.name),both=w.filter(function(x){return sw.indexOf(x)>=0;}).length;
    var jac=both/Math.max(1,new Set(w.concat(sw)).size);
    // every word typed appears in the name ("Escape Innsmouth" in Escape from Innsmouth): strong
    var subset=w.length&&w.every(function(x){return sw.indexOf(x)>=0;})?0.9:0;
    // one name inside the other as plain text: only as strong as the share of the longer name it covers
    var contain=(sk.length>=5&&k.length>=5&&(sk.indexOf(k)>=0||k.indexOf(sk)>=0))?0.55+0.35*Math.min(k.length,sk.length)/Math.max(k.length,sk.length):0;
    var spell=1-lev(k,sk)/Math.max(k.length,sk.length);
    return {s:s,score:Math.max(jac,subset,contain,spell)};
  }).filter(function(x){return x.score>=0.45;}).sort(function(a,b){return b.score-a.score||a.s.name.localeCompare(b.s.name);});
}
// A match good enough to use without asking: clearly the best, and close.
function sureMatch(c){return c.length&&(c[0].score===1||(c[0].score>=0.85&&(!c[1]||c[1].score<=c[0].score-0.1)))?c[0].s:null;}

root.MOM={PRODUCTS:PRODUCTS,OFFICIAL:OFFICIAL,VALKYRIE:VALKYRIE,INVESTIGATORS:INVESTIGATORS,INVESTIGATOR_GROUPS:INVESTIGATOR_GROUPS,isInvestigator:isInvestigator,matchInvestigator:matchInvestigator,matchScenarios:matchScenarios,sureMatch:sureMatch,slug:slug,key:key,
  productName:function(id){var p=PRODUCTS.filter(function(x){return x.id===id;})[0];return p?p.name:'';}};
})(typeof window!=='undefined'?window:globalThis);
