"""Builds scripts/tiles_index.py, the tile numbers for the packing lists, from the community
Mansions of Madness Tiles Index v5.2 PDF (https://boardgamegeek.com/filepage/147448/mansions-of-madness-tiles-index)
and Valkyrie's game content (github.com/NPBruce/valkyrie, unity/Assets/StreamingAssets/content/MoM).

The PDF's first page lists every tile side alphabetically: name, an expansion symbol, number and size. The symbols are
images, so each one is identified by the legend at the top of the page (the same image drawn beside each expansion's
name). Each Valkyrie tile side is then matched by name within its own expansion (names repeat across expansions:
there are five Libraries). Only names, numbers and expansions are kept; the PDF itself isn't stored here.

Run: pip install pdfplumber; python3 scripts/tiles-index-from-pdf.py <MansionsOfMadnessTilesIndex_v5.2.pdf> <content/MoM>
Earlier versions came from Dan's valkyrie-tools packlist catalogue; this one replaces it (and fixes Kitchen, Attic
Storage and Basement Storage, which are Beyond the Threshold small tiles)."""
import json, os, re, sys, unicodedata
import pdfplumber

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
EXPANSIONS = ['First Edition Core', 'Second Edition Core', 'Call of the Wild', 'Forbidden Alchemy', 'Beyond the Threshold',
              'Streets of Arkham', 'Sanctum of Twilight', 'Horrific Journeys', 'Path of the Serpent']
# Valkyrie content pack -> the expansion its tiles show in the index
PACK_EXPANSION = {'MoMBase': 'Second Edition Core', 'MoM1ET': 'First Edition Core', 'FAT': 'Forbidden Alchemy',
                  'CotWT': 'Call of the Wild', 'BtT': 'Beyond the Threshold', 'SoA': 'Streets of Arkham',
                  'SoT': 'Sanctum of Twilight', 'HJ': 'Horrific Journeys', 'PotS': 'Path of the Serpent'}


def read_pdf(path):
    page = pdfplumber.open(path).pages[0]
    words = page.extract_words()
    mid = lambda o: (o['top'] + o['bottom']) / 2
    legend = {}
    for im in page.images:
        if im['top'] > 100:
            continue
        line = sorted((w for w in words if abs(mid(w) - mid(im)) < 4 and w['x1'] <= im['x0'] + 1 and w['x0'] > im['x0'] - 110), key=lambda w: w['x0'])
        text = ' '.join(w['text'] for w in line)
        for e in EXPANSIONS:
            if text.endswith(e):
                legend[im['name']] = e
    rows = []
    for im in page.images:
        if im['top'] <= 100:
            continue
        line = sorted((w for w in words if abs(mid(w) - mid(im)) < 4), key=lambda w: w['x0'])
        name = ' '.join(w['text'] for w in line if w['x1'] <= im['x0'] + .5 and w['x0'] > im['x0'] - 95)
        name = re.sub(r'^\d+ [SML] ', '', name)          # the previous column's number
        num = ' '.join(w['text'] for w in line if w['x0'] >= im['x1'] - .5 and w['x0'] < im['x1'] + 30)
        m = re.match(r'^(\d+) ([SML])', num)
        if not m or im['name'] not in legend:
            sys.exit('could not read row: %r %r' % (name, num))
        rows.append((name, m.group(1) + m.group(2), legend[im['name']]))
    return rows


def norm(t):
    return re.sub(r'[^a-z0-9]', '', unicodedata.normalize('NFD', t.lower()).encode('ascii', 'ignore').decode())


def main():
    pdf, content = sys.argv[1], sys.argv[2]
    import importlib.util
    spec = importlib.util.spec_from_file_location('fp', os.path.join(HERE, 'fetch-packlists.py'))
    fp = importlib.util.module_from_spec(spec)
    sys.modules['tiles_index'] = type(sys)('tiles_index')
    sys.modules['tiles_index'].TILE_INDEX = {}
    spec.loader.exec_module(fp)
    rows = read_pdf(pdf)
    by = {(norm(n), e): i for n, i, e in rows}
    out, missing = {}, []
    for dirpath, _, files in os.walk(content):
        if 'content_pack.ini' not in files or 'tiles.ini' not in files:
            continue
        pack = fp.ini_sections(open(os.path.join(dirpath, 'content_pack.ini'), encoding='utf-8-sig').read())['ContentPack']['id']
        exp = PACK_EXPANSION.get(pack)
        for side, d in fp.ini_sections(open(os.path.join(dirpath, 'tiles.ini'), encoding='utf-8-sig').read()).items():
            if not side.startswith('TileSide') or not exp:
                continue
            name = fp.nice(d.get('name'), 'TILE') or fp.camel(side, 'TileSide')
            i = by.get((norm(name), exp))
            if i:
                out[pack + ':' + side] = i
            else:
                missing.append('%s (%s, %s)' % (side, name, exp))
    lines = ['"""Tile numbers for the packing lists: Valkyrie "pack:TileSide" -> number and size in the community',
             'Mansions of Madness Tiles Index v5.2 (https://boardgamegeek.com/filepage/147448/mansions-of-madness-tiles-index).',
             'Generated by scripts/tiles-index-from-pdf.py from that PDF and Valkyrie\'s game content; do not edit by hand.',
             'First used in Dan\'s valkyrie-tools packlist (github.com/maniac782/valkyrie-tools)."""',
             'TILE_INDEX = {']
    lines += ['    %s: %s,' % (json.dumps(k), json.dumps(v)) for k, v in sorted(out.items())]
    lines += ['}', '# sides Valkyrie has that the index doesn\'t number:', '# ' + '; '.join(sorted(missing)), '']
    open(os.path.join(HERE, 'tiles_index.py'), 'w').write('\n'.join(lines))
    print('index rows %d; Valkyrie sides numbered %d; not in the index: %s' % (len(rows), len(out), ', '.join(missing) or 'none'))


if __name__ == '__main__':
    main()
