"""Mansions of Madness tile index: which physical tile each Valkyrie tile side is, by the community
Mansions of Madness Tiles Index v5.2 (https://boardgamegeek.com/filepage/147448/mansions-of-madness-tiles-index).
Copied from Dan's own valkyrie-tools packlist (github.com/maniac782/valkyrie-tools, packlist/valkyrie_packlist.py);
add sides there and here. TileSide -> (size, index, expansion name as printed on the box)."""

TILE_INFO: dict[str, tuple[str, str, str]] = {
    # ===== Core (MAD20) =====
    "TileSideAlley1": ("S", "1S", "Core"),
    "TileSideBedroom1": ("S", "1S", "Core"),
    "TileSideAlley2": ("S", "2S", "Core"),
    "TileSideBedroom2": ("S", "2S", "Core"),
    "TileSideBellTower": ("S", "3S", "Core"),
    "TileSideStreetCorner1": ("S", "3S", "Core"),
    "TileSideBilliardsRoom": ("S", "4S", "Core"),
    "TileSideAlleyEnd": ("S", "4S", "Core"),
    "TileSideEntryHall": ("S", "11S", "Core"),
    "TileSideStreetCorner2": ("S", "11S", "Core"),
    "TileSideHall1": ("S", "14S", "Core"),
    "TileSideDock2": ("S", "14S", "Core"),
    "TileSideHall2": ("S", "15S", "Core"),
    "TileSideDock1": ("S", "15S", "Core"),
    "TileSideHallCorner1": ("S", "16S", "Core"),
    "TileSideAlleyCorner1": ("S", "16S", "Core"),
    "TileSideHallCorner2": ("S", "17S", "Core"),
    "TileSideAlleyCorner2": ("S", "17S", "Core"),
    "TileSideBathroom": ("S", "18S", "Core"),
    "TileSideStreet1": ("S", "18S", "Core"),
    "TileSideHallEnd": ("S", "19S", "Core"),
    "TileSideStreetCorner3": ("S", "19S", "Core"),
    "TileSideHallStairs": ("S", "20S", "Core"),
    "TileSideStreet2": ("S", "20S", "Core"),
    "TileSideLibrary": ("S", "21S", "Core"),
    "TileSideYard1": ("S", "21S", "Core"),
    "TileSideOffice": ("S", "23S", "Core"),
    "TileSideHouseBoat": ("S", "23S", "Core"),
    "TileSideStudy": ("S", "31S", "Core"),
    "TileSideRentalDock": ("S", "31S", "Core"),
    "TileSideRentalShack": ("S", "31S", "Core"),
    "TileSideYard2": ("S", "32S", "Core"),
    "TileSideBeach": ("S", "32S", "Core"),
    "TileSideMoldyShack": ("S", "32S", "Core"),
    "TileSideAttic": ("M", "1M", "Core"),
    "TileSideParkPond": ("M", "1M", "Core"),
    "TileSideAtticStairs": ("M", "1M", "Core"),
    "TileSideBallroom": ("M", "5M", "Core"),
    "TileSideWarehouse": ("M", "5M", "Core"),
    "TileSideBasement": ("M", "7M", "Core"),
    "TileSideFleaMarket": ("M", "7M", "Core"),
    "TileSideConservatory": ("M", "8M", "Core"),
    "TileSideStorefront": ("M", "8M", "Core"),
    "TileSideDiningRoom": ("M", "9M", "Core"),
    "TileSideTownSquare": ("M", "9M", "Core"),
    "TileSideKitchen": ("M", "9M", "Core"),
    "TileSideInteriorHall": ("M", "15M", "Core"),
    "TileSideRootCellar": ("M", "15M", "Core"),
    "TileSideLobby": ("M", "16M", "Core"),
    "TileSideToolShed": ("M", "16M", "Core"),
    "TileSideLounge": ("M", "17M", "Core"),
    "TileSidePier": ("M", "17M", "Core"),

    # ===== Recurring Nightmares (MAD01) =====
    "TileSideCeremonyRoom": ("S", "8S", "Recurring Nightmares"),
    "TileSideNursery": ("S", "8S", "Recurring Nightmares"),
    "TileSideBathroom2": ("S", "8S", "Recurring Nightmares"),
    "TileSideCave1": ("S", "5S", "Recurring Nightmares"),
    "TileSideHallway4": ("S", "5S", "Recurring Nightmares"),
    "TileSideCave2": ("S", "6S", "Recurring Nightmares"),
    "TileSideHallway3": ("S", "6S", "Recurring Nightmares"),
    "TileSideCave3": ("S", "7S", "Recurring Nightmares"),
    "TileSideChasm": ("S", "9S", "Recurring Nightmares"),
    "TileSideHallway2": ("S", "9S", "Recurring Nightmares"),
    "TileSideCrypt": ("S", "10S", "Recurring Nightmares"),
    "TileSideHallway1": ("S", "10S", "Recurring Nightmares"),
    "TileSideFurnaceRoom": ("S", "12S", "Recurring Nightmares"),
    "TileSideMasterBedroom": ("S", "12S", "Recurring Nightmares"),
    "TileSideHallway5": ("S", "13S", "Recurring Nightmares"),
    "TileSideGuestBedroom": ("S", "29S", "Recurring Nightmares"),
    "TileSideStorageCloset": ("S", "29S", "Recurring Nightmares"),
    "TileSideSecretPassage": ("S", "29S", "Recurring Nightmares"),
    "TileSideAtticLoft": ("M", "2M", "Recurring Nightmares"),
    "TileSideChapel": ("M", "2M", "Recurring Nightmares"),
    "TileSideBasementLanding": ("M", "6M", "Recurring Nightmares"),
    "TileSideBasementStairs": ("M", "6M", "Recurring Nightmares"),
    "TileSideAtticStorage": ("M", "6M", "Recurring Nightmares"),
    "TileSideBasementStorage": ("M", "6M", "Recurring Nightmares"),
    "TileSideTowerRoom": ("M", "6M", "Recurring Nightmares"),
    "TileSideTowerStairs": ("M", "6M", "Recurring Nightmares"),
    "TileSideGarden": ("M", "10M", "Recurring Nightmares"),
    "TileSideEntryway": ("M", "10M", "Recurring Nightmares"),
    "TileSideFrontPorch": ("M", "11M", "Recurring Nightmares"),
    "TileSideFrontPath": ("M", "11M", "Recurring Nightmares"),
    "TileSideFreezer": ("M", "11M", "Recurring Nightmares"),
    "TileSideOperatingRoom": ("M", "11M", "Recurring Nightmares"),
    "TileSideLaboratory": ("M", "11M", "Recurring Nightmares"),
    "TileSideGraveyard": ("M", "13M", "Recurring Nightmares"),
    "TileSideKitchenStorage": ("M", "13M", "Recurring Nightmares"),
    "TileSideCornerHallway1": ("M", "21M", "Recurring Nightmares"),
    "TileSideCornerHallway2": ("M", "21M", "Recurring Nightmares"),
    "TileSidePatio": ("M", "21M", "Recurring Nightmares"),
    "TileSideFoyer": ("L", "2L", "Recurring Nightmares"),
    "TileSideMudRoom": ("L", "2L", "Recurring Nightmares"),
    "TileSideFrontYard": ("L", "2L", "Recurring Nightmares"),

    # ===== Suppressed Memories (MAD06) =====
    "TileSideGraveyard2": ("S", "13S", "Suppressed Memories"),
    "TileSideHoldingCell": ("S", "22S", "Suppressed Memories"),
    "TileSideObservationRoom": ("S", "22S", "Suppressed Memories"),
    "TileSideMedicalStorage": ("S", "22S", "Suppressed Memories"),
    "TileSideCaveBend": ("S", "24S", "Suppressed Memories"),
    "TileSideOldOak": ("S", "24S", "Suppressed Memories"),
    "TileSideCaveEntrance": ("S", "25S", "Suppressed Memories"),
    "TileSidePigpen": ("S", "25S", "Suppressed Memories"),
    "TileSideOldWell": ("S", "26S", "Suppressed Memories"),
    "TileSideRiverBend1": ("S", "26S", "Suppressed Memories"),
    "TileSideRiverBend2": ("S", "26S", "Suppressed Memories"),
    "TileSideDarkPath": ("S", "27S", "Suppressed Memories"),
    "TileSideOuthouse": ("S", "27S", "Suppressed Memories"),
    "TileSideRiverRapids1": ("S", "27S", "Suppressed Memories"),
    "TileSideRiverRapids2": ("S", "27S", "Suppressed Memories"),
    "TileSideCampsite": ("S", "28S", "Suppressed Memories"),
    "TileSideScarecrow": ("S", "28S", "Suppressed Memories"),
    "TileSideRottedPath": ("S", "30S", "Suppressed Memories"),
    "TileSideRottedPorch": ("S", "30S", "Suppressed Memories"),
    "TileSideSpruceGrove": ("S", "30S", "Suppressed Memories"),
    "TileSideBackPath": ("M", "3M", "Suppressed Memories"),
    "TileSideControlRoom": ("M", "3M", "Suppressed Memories"),
    "TileSideGreenhouse": ("M", "3M", "Suppressed Memories"),
    "TileSideHiddenLaboratory": ("M", "3M", "Suppressed Memories"),
    "TileSideGeneratorRoom": ("M", "12M", "Suppressed Memories"),
    "TileSideOperatingTheater": ("M", "12M", "Suppressed Memories"),
    "TileSideAbandonedShack": ("M", "14M", "Suppressed Memories"),
    "TileSideHilltop": ("M", "14M", "Suppressed Memories"),
    "TileSideOldOrchard": ("M", "14M", "Suppressed Memories"),
    "TileSideMarshland": ("M", "18M", "Suppressed Memories"),
    "TileSideRitualSite": ("M", "18M", "Suppressed Memories"),
    "TileSidePond": ("M", "19M", "Suppressed Memories"),
    "TileSideTortureChamber": ("M", "19M", "Suppressed Memories"),
    "TileSideDungeonCave": ("M", "19M", "Suppressed Memories"),
    "TileSideDungeonCell": ("M", "19M", "Suppressed Memories"),
    "TileSideMorgue": ("M", "20M", "Suppressed Memories"),
    "TileSideQuarantineRoom": ("M", "20M", "Suppressed Memories"),
    "TileSideRooftop": ("M", "20M", "Suppressed Memories"),
    "TileSideForestEdge": ("L", "1L", "Suppressed Memories"),
    "TileSideMillYard": ("L", "1L", "Suppressed Memories"),
    "TileSideOldForest": ("L", "1L", "Suppressed Memories"),
    "TileSideSawmill": ("L", "1L", "Suppressed Memories"),
    "TileSideWaterwheel": ("L", "1L", "Suppressed Memories"),
    "TileSideBarn": ("L", "3L", "Suppressed Memories"),
    "TileSideBarnyard": ("L", "3L", "Suppressed Memories"),
    "TileSideRiverCrossing1": ("L", "3L", "Suppressed Memories"),
    "TileSideRiverCrossing2": ("L", "3L", "Suppressed Memories"),
    "TileSideCoveredBridge": ("L", "3L", "Suppressed Memories"),

    # ===== Beyond the Threshold (MAD23) =====
    "TileSideHallCorner": ("S", "35S", "Beyond the Threshold"),
    "TileSideHallCorner3": ("S", "18S", "Beyond the Threshold"),
    "TileSideBalcony": ("S", "33S", "Beyond the Threshold"),
    "TileSidePorch": ("S", "34S", "Beyond the Threshold"),
    "TileSideCoatRoom": ("M", "4M", "Beyond the Threshold"),
    "TileSideBackyard": ("M", "4M", "Beyond the Threshold"),
    "TileSideGallery": ("M", "4M", "Beyond the Threshold"),
    "TileSideStorageShed": ("M", "4M", "Beyond the Threshold"),
    "TileSideFrontStreet": ("M", "8M", "Beyond the Threshold"),
    "TileSideGardenPath": ("M", "8M", "Beyond the Threshold"),
    "TileSideSmallBedroom1": ("M", "15M", "Beyond the Threshold"),
    "TileSideSmallBedroom2": ("M", "15M", "Beyond the Threshold"),
    "TileSideSnackShack": ("M", "17M", "Beyond the Threshold"),
    "TileSideExhibitEntrance": ("L", "4L", "Beyond the Threshold"),
    "TileSideDiner": ("L", "4L", "Beyond the Threshold"),

    # ===== Streets of Arkham (MAD25) =====
    "TileSideAlley": ("S", "43S", "Streets of Arkham"),
    "TileSideStreetCorner": ("S", "48S", "Streets of Arkham"),
    "TileSideBandstand": ("M", "24M", "Streets of Arkham"),
    "TileSideGeneralShop": ("M", "25M", "Streets of Arkham"),
    "TileSideShopStorage": ("M", "25M", "Streets of Arkham"),
    "TileSideStudio": ("M", "25M", "Streets of Arkham"),
    "TileSideStudioStorage": ("M", "25M", "Streets of Arkham"),
    "TileSideClassroom1": ("M", "26M", "Streets of Arkham"),
    "TileSideCafe": ("M", "27M", "Streets of Arkham"),

    # ===== Sanctum of Twilight (MAD26) =====
    "TileSideExhibit3": ("M", "22M", "Sanctum of Twilight"),
    "TileSideMainExhibit": ("M", "23M", "Sanctum of Twilight"),
    "TileSidePool": ("M", "28M", "Sanctum of Twilight"),
    "TileSideProw": ("M", "29M", "Sanctum of Twilight"),
    "TileSideViewingRoom2": ("M", "29M", "Sanctum of Twilight"),
    "TileSideThroneChamber": ("M", "31M", "Sanctum of Twilight"),
    "TileSideRiverEdge": ("M", "31M", "Sanctum of Twilight"),
    "TileSideStatueChamber": ("M", "32M", "Sanctum of Twilight"),
    "TileSideRuinedHut": ("M", "32M", "Sanctum of Twilight"),
    "TileSideCrackedChamber": ("M", "33M", "Sanctum of Twilight"),
    "TileSideTempleStairs": ("M", "33M", "Sanctum of Twilight"),
    "TileSideCrumblingPlaza": ("M", "34M", "Sanctum of Twilight"),
    "TileSidePoolChamber": ("M", "34M", "Sanctum of Twilight"),
    "TileSideMosaicChamber": ("M", "35M", "Sanctum of Twilight"),
    "TileSideRopeBridge": ("M", "35M", "Sanctum of Twilight"),

    # ===== Horrific Journeys (MAD27) =====
    "TileSideCabin": ("S", "23S", "Horrific Journeys"),
    "TileSideEngineRoom": ("M", "30M", "Horrific Journeys"),
    "TileSideEngineStairs": ("M", "30M", "Horrific Journeys"),
    "TileSideStation": ("M", "30M", "Horrific Journeys"),
    "TileSideStationBooth": ("M", "30M", "Horrific Journeys"),
    "TileSideStationPlatform": ("M", "30M", "Horrific Journeys"),

    # ===== Path of the Serpent (MAD28) =====
    "TileSideLab": ("M", "24M", "Path of the Serpent"),
    "TileSideJungleRuins3": ("M", "32M", "Path of the Serpent"),
    "TileSideAbandonedHut": ("M", "36M", "Path of the Serpent"),
    "TileSideClearing2": ("M", "36M", "Path of the Serpent"),
    "TileSidePit": ("M", "36M", "Path of the Serpent"),
    "TileSidePitLedge": ("M", "36M", "Path of the Serpent"),
}
